### ISSUE TITLE
Add to AtomLinter Group

### ISSUE THREAD

**Issue by njlg** [AtomLinter/atom-linter-perlcritic#2]
Looks like most linters are part of the AtomLinter group (https://github.com/AtomLinter). Maybe we should get this project added to that group too?

**Comment by Arcanemagus** [comment]
@whity if you are ever interested in this, I'm one of the owners on the AtomLinter org and can take care of this with you. The general procedure is outlined [here](https://github.com/AtomLinter/Meta/wiki/Migrating-a-repository).

**Comment by whity** [comment]
Hi @Arcanemagus if you don't mind, that would be nice.

**Comment by Arcanemagus** [comment]
The first method is the best since nothing will break and all old links will redirect to the new location. I'm on [Atom's Slack](http://atom-slack.herokuapp.com/) if you want to chat there 😉.
