### ISSUE TITLE
Bug: unhandled error being thrown from Helpers.rangeFromLineNumber

### ISSUE THREAD

**Issue by mshirlaw** [AtomLinter/atom-linter-perlcritic#35]
I am seeing the following error fairly consistently:

<img width="464" alt="screen shot 2016-12-09 at 11 37 22 am" src="https://cloud.githubusercontent.com/assets/1466457/21033449/6c7a5f46-be04-11e6-86cc-c798a8daaf66.png">

Steps to reproduce:
1. Create a hash 
2. Add a key/value pair
3. Add another key/value pair
4. Start to backspace 

It seems that `Helpers.rangeFromLineNumber` can throw an error which is not handled. Given that the linter is repeatedly running this code, this error will spawn multiple warnings on the screen reporting the same issue. A potential solution could be as follows (line 115 in `lib/init.js`):

``` 
try {
   messages.push({
      type: atom.config.get('linter-perlcritic.level'),
      text,
      filePath,
      range: Helpers.rangeFromLineNumber(textEditor, line, col),
   });
} catch (error) {
   // handle error here or at least only show the error once ?
}
```
Would like to hear if other people have experienced this error and any ideas as to the best approach to fix?

**Comment by Arcanemagus** [comment]
It's only been implemented in `linter-eslint` and `linter-flake8` so far, but I eventually want to move all the providers to something like this: https://github.com/AtomLinter/linter-flake8/pull/277/files

Essentially messages like this get translated into a Linter message that tells the user an invalid point was returned from the linter provider (`Perl::Critic` here), and provides a link that automatically generates an issue for the user including debug information.

As a note, that error is thrown when the linter program (`Perl::Critic`) gives a point that doesn't exist in the document being edited, so generally it's a bug in the linter program causing this.

**Comment by Arcanemagus** [comment]
Ah a potential [false positive check](https://github.com/AtomLinter/linter-flake8/blob/013350b807282c997f34c082e688e21684fe58a0/lib/main.js#L240-L243) looks like it hasn't been put in place here yet. Adding that will prevent the case of the user editing the document after it was sent to the linter but before the results came back causing points that were valid as far as the linter is concerned showing as invalid.
