### ISSUE TITLE
Error: Failed to spawn command perlcritic

### ISSUE THREAD

**Issue by mshirlaw** [AtomLinter/atom-linter-perlcritic#42]
Seeing a whole lot of this after the most recent update:
 
![error](https://cloud.githubusercontent.com/assets/1466457/26751432/b109e548-487c-11e7-8672-032af5d61fab.jpg)

`perlcritic` is definitely installed & included on `$PATH` . 

Copying full path to `perlcritic` into 

`Atom > Preferences > Packages > linter-perlcritic > Settings` 

does not solve the issue. Any ideas?

After a bit more reading it looks like the `atom-linter` base package should automatically determine `$PATH` when atom launched so I am not sure why this has suddenly become an issue with this release. Weird

**Comment by whity** [comment]
hi @Arcanemagus, did you already take a look at this?

**Comment by Arcanemagus** [comment]
@mshirlaw Are you still having issues with this? If so, can you place a breakpoint [here](https://github.com/AtomLinter/atom-linter-perlcritic/blob/v1.4.2/lib/init.js#L129) in Atom's Developer Tools and see what the `command` variable contains? It should match that setting.
