### ISSUE TITLE
Error: Failed to spawn command /usr/bin/perlcritic. Make sure /usr/bin/perlcritic is installed and on your PATH

### ISSUE THREAD

**Issue by aboettger-tuhh** [AtomLinter/atom-linter-perlcritic#46]
```
$ which perlcritic
/usr/bin/perlcritic
```
But the error message resists:

```
Error: Failed to spawn command /usr/bin/perlcritic. Make sure /usr/bin/perlcritic is installed and on your PATH
```

**Comment by MartinTrubelik** [comment]
`perldoc -l perlcritic`
Find your perlcritic location and copy it to settings of the linter.
In my case the path is:
`/usr/local/Cellar/perl/5.26.1/bin/perlcritic`

**Comment by whity** [comment]
@aboettger-tuhh still having this problem? Closing this for now, feel free to reopen.
