### ISSUE TITLE
Noisy errors when perl compilation fails

### ISSUE THREAD

**Issue by mekazu** [AtomLinter/atom-linter-perlcritic#6]
Could we hide errors if a given Perl Critic module fails to compile the package? Or at least make the warning less noisy?

**Comment by whity** [comment]
hi, could you explain more what you pretend? can you give an example.
thanks.

**Comment by mshirlaw** [comment]
Definitely a very intrusive error warning. ![screen shot 2016-12-02 at 2 27 00 pm](https://cloud.githubusercontent.com/assets/1466457/20822045/914ddae6-b89b-11e6-9a20-ddc8f3c976d3.png)

**Comment by Arcanemagus** [comment]
That error is telling you that parts of Perl::Critic itself are missing, which has nothing to do with your code.

Can you try (re)installing the TryTiny policy?

**Comment by mshirlaw** [comment]
It isn't the error message that is the problem - it is trivial to fix. It is the SIZE of the warning box that becomes annoying. This error will also spawn multiple warning boxes that cover most of the screen. Is it possible to make this warning and others like it less intrusive? I.e does it need the entire stack trace ? @arcanemagus

**Comment by Arcanemagus** [comment]
The error is just the `stderr` output from running `perlcritic`, so it doesn't need the full stack trace, a `try`/`catch` block could be placed around [here](https://github.com/AtomLinter/atom-linter-perlcritic/blob/8821f54a12d23f01c47a14260f4e771cab7b15dd/lib/init.js#L61-L69) and this error transformed into a cleaner form.

**Comment by mshirlaw** [comment]
Yes this is what I'm getting at. If I get time I'll submit a pull request 👍thanks

**Comment by mshirlaw** [comment]
Addressed in #34

**Comment by Arcanemagus** [comment]
Leaving this open for the moment due to https://github.com/AtomLinter/atom-linter-perlcritic/pull/34#issuecomment-264728460 and onwards.

**Comment by whity** [comment]
I think we can close this, right?

**Comment by mshirlaw** [comment]
I think yes 👍
