### ISSUE TITLE
Change linter severity to match perlcritic severity

### ISSUE THREAD

**Issue by MaelStor** [AtomLinter/atom-linter-perlcritic#66]
This colorizes the dots and underlines in the editor differently based on the original severity and helps to rate the importance.

I tested the mapping [1,2] -> error, [3] -> warning, [4,5] -> info and feel comfortable with it.

**Comment by whity** [comment]
Hello, can I ask you to provide a pull request? Thanks.

**Comment by MaelStor** [comment]
Yes sure. I'm a bit busy right now but I'll try.
